version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_ADDRESS=redis:6379
      - DB_PASS=yourpassword
    depends_on:
      - redis
    networks:
      - url_shortener_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
    driver: bridge